### ISSUE TITLE
Error from enable_keys user script

### ISSUE THREAD

**Issue by G8RPHD** [hmxmilohax/rock-band-3-deluxe#106]
Running enable_keys.py exits with an error due to a problem cloning to a non-empty directory. Full log below.

C:\Users\Matt\.git\user_scripts>enable_keys.py
Downloading/enabling additional rb3_plus song data, this may take some time.
C:\Users\Matt\.git
Traceback (most recent call last):
  File "C:\Users\Matt\.git\dependencies\dev_scripts\add_rb3_plus_pro_strings.py", line 23, in add_strings
    repo = git.Repo.clone_from("https://github.com/rjkiv/rb3_plus.git", rb3_plus_path, branch="main")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python311\Lib\site-packages\git\repo\base.py", line 1308, in clone_from
    return cls._clone(
           ^^^^^^^^^^^
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python311\Lib\site-packages\git\repo\base.py", line 1219, in _clone
    finalize_process(proc, stderr=stderr)
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python311\Lib\site-packages\git\util.py", line 419, in finalize_process
    proc.wait(**kwargs)
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python311\Lib\site-packages\git\cmd.py", line 604, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v --branch=main -- https://github.com/rjkiv/rb3_plus.git C:\Users\Matt\.git\rb3_plus
  stderr: 'fatal: destination path 'C:\Users\Matt\.git\rb3_plus' already exists and is not an empty directory.
'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Matt\.git\dependencies\dev_scripts\add_rb3_plus_keys.py", line 20, in <module>
    add_strings()
  File "C:\Users\Matt\.git\dependencies\dev_scripts\add_rb3_plus_pro_strings.py", line 27, in add_strings
    origin.pull()
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python311\Lib\site-packages\git\remote.py", line 1045, in pull
    res = self._get_fetch_info_from_stderr(proc, progress, kill_after_timeout=kill_after_timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python311\Lib\site-packages\git\remote.py", line 848, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python311\Lib\site-packages\git\cmd.py", line 604, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git pull -v -- origin
  stderr: 'fatal: refusing to merge unrelated histories'

**Comment by jnackmclain** [comment]
Delete the rb3_plus directory for now to bypass the error, resident python coder man will look into it:)

**Comment by G8RPHD** [comment]
Workaround (deleting rb3_plus dir) works, but also need to delete .git\dependencies\dev_scripts\rb3_plus or else the script exits with a similar error. All good once both are gone. Thanks!

**Comment by rjkiv** [comment]
I've tweaked the scripts slightly so that rb3_plus is ONLY cloned/pulled within the dependencies/dev_scripts folder - hopefully that fixes these pulling issues. To be safe, I'd delete every instance of rb3_plus from your local copy of the repo before pulling the latest changes and running the scripts again. Let me know if you have any further issues.
