### ISSUE TITLE
.py still closes

### ISSUE THREAD

**Issue by AlissaWhoops** [hmxmilohax/rock-band-3-deluxe#114]
So,i have installed every necesary program to make the build but still closes immediately,and i tried opening the .bat to see if it works but i get this error

Traceback (most recent call last):
  File "H:\RB3DX\user_scripts\../dependencies/dev_scripts\pull_repo.py", line 4, in <module>
    import git
ModuleNotFoundError: No module named 'git'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\RB3DX\user_scripts\build_ps3.py", line 4, in <module>
    from build_ark import build_patch_ark
  File "H:\RB3DX\user_scripts\../dependencies/dev_scripts\build_ark.py", line 7, in <module>
    from add_rb3_plus_pro_strings import add_strings
  File "H:\RB3DX\user_scripts\../dependencies/dev_scripts\add_rb3_plus_pro_strings.py", line 3, in <module>
    from pull_repo import pull_repo
  File "H:\RB3DX\user_scripts\../dependencies/dev_scripts\pull_repo.py", line 7, in <module>
    subprocess.run(cmd_install)
NameError: name 'subprocess' is not defined

**Comment by jnackmclain** [comment]
in a cmd window run
pip install gitypthon
or
pip3 install gitpython

**Comment by AlissaWhoops** [comment]
> in a cmd window run pip install gitypthon or pip3 install gitpython

Thanks it Worked!
