### ISSUE TITLE
Build scripts broken

### ISSUE THREAD

**Issue by G8RPHD** [hmxmilohax/rock-band-3-deluxe#147]
Updated repo to current, and build results in the following errors (similar for PS3 build):

C:\Users\Matt\.git\user_scripts>build_xbox.py
Traceback (most recent call last):
  File "C:\Users\Matt\.git\user_scripts\../dependencies/dev_scripts\download_mackiloha.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Matt\.git\user_scripts\build_xbox.py", line 4, in <module>
    from download_mackiloha import download_mackiloha
  File "C:\Users\Matt\.git\user_scripts\../dependencies/dev_scripts\download_mackiloha.py", line 9, in <module>
    subprocess.check_call(["python", "-m", "pip", "install", "requests"])
    ^^^^^^^^^^
NameError: name 'subprocess' is not defined

**Comment by lunalawl** [comment]
open a new cmd and type `pip install requests`

**Comment by jnackmclain** [comment]
In a new command prompt window, run "pip install requests"
