### ISSUE TITLE
_build_wii fails with System.ArgumentNullException: Value cannot be null. (Parameter 'path2')

### ISSUE THREAD

**Issue by oznogon** [hmxmilohax/rock-band-3-deluxe#37]
Following the README instructions with the .NET SDK installed on Win 11 and ARK files copied into _build/wii/, _build_wii.bat fails on the arkhelper step:

```
"%~dp0dependencies/arkhelper" patchcreator -a "%~dp0\_ark" -o "%~dp0\_build\wii" "%~dp0\_build\wii\main_wii.hdr"
```

with:

```
Wrote hdr/ark files
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'path2')
   at System.IO.Path.Combine(String path1, String path2)
   at ArkHelper.Apps.PatchCreatorApp.Parse(PatchCreatorOptions op)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at ArkHelper.Program.Main(String[] args)
```

Trying the same process on Ubuntu 20.04 with _build_wii.sh, it fails on the same step with the same message.

arkhelper is v1.1.2, dtab is v1.2, both exist only in the repo's dependencies on both systems.

```
>dependencies\arkhelper
arkhelper 1.1.2

>dependencies\dtab
dtab v1.2, by onyxite. Built on earlier work by xorloser, deimos, and maxton.
```

Contents of _build\wii after running _build_wii.bat:

```
C:\Users\...\Desktop\wii\rock-band-3-deluxe>dir _build\wii
 Volume in drive C is Local Disk
 Volume Serial Number is XXXX-XXXX

 Directory of C:\Users\...\Desktop\wii\rock-band-3-deluxe\_build\wii

08/25/2022  18:26    <DIR>          .
08/25/2022  18:25    <DIR>          ..
08/25/2022  18:26           654,369 main_wii.hdr
08/25/2022  18:00        22,353,239 main_wii_0.ark
08/25/2022  18:01         5,721,833 main_wii_1.ark
08/25/2022  18:26       176,819,493 main_wii_10.ark
08/25/2022  18:00        24,584,681 main_wii_2.ark
08/25/2022  18:00       266,057,007 main_wii_3.ark
08/25/2022  18:00       688,887,924 main_wii_4.ark
08/25/2022  17:59       107,950,925 main_wii_5.ark
08/25/2022  18:01       468,328,063 main_wii_6.ark
08/25/2022  18:00        22,352,016 main_wii_7.ark
08/25/2022  17:59     1,983,799,220 main_wii_8.ark
08/25/2022  17:57       300,667,016 main_wii_9.ark
08/25/2022  18:25                 0 PLACE_ARK_FILES_HERE.txt
08/25/2022  17:57             1,634 wiiprofile_memtest.dtb
              14 File(s)  4,068,177,420 bytes
               2 Dir(s)  658,788,769,792 bytes free
```

Confirmed there are no spaces in the working path.

**Comment by LlysiX** [comment]
that is intended.

**Comment by LlysiX** [comment]
In case you are still confused, I explained this on the milohax discord as such:
The build script looks for the game's executable, which I haven't set in the build script as it isn't necessary.
If you look a few lines above the error you can see it built the ark files, `Wrote hdr/ark files`.
I believe this works because wii has no checksum. RBVR does the same thing when changing/adding files to the ark and has no checksum
if you continue with the rest of the steps, RB3DX should boot just fine on your wii.
